// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwk1VZKOaclVA5XrKSBUxsBlv-SNUCmqQ',
    appId: '1:253331236563:web:c5e26e25f855fe83f05626',
    messagingSenderId: '253331236563',
    projectId: 'cypherkey',
    authDomain: 'cypherkey.firebaseapp.com',
    storageBucket: 'cypherkey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs8wkCRcVTaPy6NwJaAmAr6Eh3thqP7RE',
    appId: '1:253331236563:android:232b3bf47d428817f05626',
    messagingSenderId: '253331236563',
    projectId: 'cypherkey',
    storageBucket: 'cypherkey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdXAJv82mBJ0kQr1Gae4GRF682ozOZKqE',
    appId: '1:253331236563:ios:be2c7cb8df8d0db6f05626',
    messagingSenderId: '253331236563',
    projectId: 'cypherkey',
    storageBucket: 'cypherkey.appspot.com',
    iosBundleId: 'com.example.cipherkey',
  );
}
